import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ClientPathnameChecker from "./components/ClientPathnameChecker";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["variable"],
});

export const metadata = {
  title: "IBOS Finance",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <ClientPathnameChecker>{children}</ClientPathnameChecker>
      </body>
    </html>
  );
}
