"use client";
import React, { useState, useEffect } from "react";
import Cookies from "js-cookie";
import PageHeader from "../components/main/PageHeader";
import { Card } from "@tremor/react";

export default function Recommendations() {
  const [recommendations, setRecommendations] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecommendations = async () => {
      const token = Cookies.get("token");

      try {
        const response = await fetch(
          "https://ibos-deploy.vercel.app/ai-recommendations",
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
        );

        if (response.ok) {
          const result = await response.json();
          setRecommendations(result.data.recommendation);
        } else {
          console.error("Failed to fetch recommendations");
        }
      } catch (error) {
        console.error("Error fetching recommendations:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchRecommendations();
  }, []);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="flex space-x-2">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-solid border-violet-500 border-t-transparent"></div>
        </div>
      </div>
    );
  }

  if (recommendations === null) {
    return (
      <div>
        <PageHeader
          title="Recommendations"
          subtitle="AI Generated Recommendations"
        />
        <div className="flex min-h-[calc(100vh-250px)] items-center justify-center p-4">
          <p className="text-center text-xl font-bold text-gray-500">
            There are currently no recommendations available. Recommendations
            are generated by AI. Please add your favorite deals.
          </p>
        </div>
      </div>
    );
  }

  return (
    <section className="p-4 md:p-6 lg:p-8">
      <PageHeader
        title="Recommendations"
        subtitle="AI Generated Recommendations"
      />
      <div className="mt-6 grid grid-cols-2 gap-6 max-xl:grid-cols-1">
        {recommendations.map((rec, index) => (
          <Card
            key={index}
            className="min-w-full border-stone-200 bg-white shadow-lg dark:border-main-dark-secondary dark:bg-main-dark-secondary dark:text-white"
          >
            <div className="p-4">
              <h4 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                #{rec.rank} - {rec.companyName} ({rec.symbol})
              </h4>
              <ul className="mt-2 list-disc pl-5 text-sm text-gray-600 dark:text-gray-300">
                {rec.reasons.map((reason, reasonIndex) => (
                  <li key={reasonIndex} className="mt-1">
                    {reason}
                  </li>
                ))}
              </ul>
            </div>
          </Card>
        ))}
      </div>
    </section>
  );
}
